### ISSUE TITLE
Is RSA 4096bit supported?

### ISSUE THREAD

**Issue by VassilisM** [rustls/rustls-cng#1]
Hello.
Any ideas why I could be getting "Error code 80090016" when trying to access an RSA-4096bit certificate from store?
The certificate from the pfx file before imported, is being read and used like a charm.

And, would an ed25519 certificate be supported?
At the moment I cannot even import it in store though, but the pfx returns the same error code as above.
Thank you.

UPDATE: Interesting... While the RSA-2048bit imported certificate has non-exportable key, it works. The 4096bit does not. It worked with nothing checked or, of course, with exportable. It works with non-exportable key if run as administrator.

What can you make out of this?
Could it be that the non-exportable 4K key is stored in the TPM, which requires administrative rights to be accessed?

**Comment by ancwrd1** [comment]
Hi, as far as I know there are some limitations on Windows, namely:

```text
4096-bit key storage is supported only in the Software Key Storage Provider (KSP). The following does not support storing keys of this size:
    The hardware TPM (Trusted Platform Module). As a workaround, you can use the Software KSP for key storage.
    Windows Hello for Business. There is no workaround at this time.
```

Not sure if it's applicable in your case.
Source: https://learn.microsoft.com/en-us/mem/intune/protect/certificates-profile-scep

**Comment by VassilisM** [comment]
Cool thanks, I will check it out.
What about ed25519?

**Comment by ancwrd1** [comment]
Looks like the CNG API has at least *some* support for 25519 curves: https://learn.microsoft.com/en-us/windows/win32/seccng/cng-named-elliptic-curves

But I haven't tried it, tbh.

**Comment by VassilisM** [comment]
Very well. Thank you. (I will let you know if and when I try ;-))
