### ISSUE TITLE
Consider adding CI?

### ISSUE THREAD

**Issue by cpu** [rustls/rustls-cng#3]
Hi there,

👋 I've been running [zizmor](https://woodruffw.github.io/zizmor/) across the varios Rustls org repos this morning and was surprised when I came to this repo that there's no CI at all.

Is that something you've considered adding? There's a lot of example configuration to draw from across the other Rustls org repos.

**Comment by ancwrd1** [comment]
That was in the roadmap, yes :)
Thanks for reminding, I'll go ahead and add it.

**Comment by cpu** [comment]
Thanks!
